version: "3.3"

services:

  php:
    image: abiosoft/caddy:php
    volumes:
     - ./:/srv
     - ./Caddyfile:/etc/Caddyfile
    ports:
      - 80:2015
    environment:
      MY_ENV: foobaz

  react:
    image: php:7-alpine
    volumes:
     - ./:/srv
    ports:
      - 81:80
    command: /srv/bin/serve.php
    environment:
      MY_ENV: foobaz
