version: "3.3"

services:

  caddy:
    image: abiosoft/caddy:php
    volumes:
     - ./:/srv
     - ./infra/Caddyfile:/etc/Caddyfile
    ports:
      - 81:2015
    environment:
      MY_ENV: foobaz

  apache:
    image: php:7.0-apache
    volumes:
     - ./:/srv
    ports:
      - 82:80
    command: /srv/infra/apache.sh
    environment:
      MY_ENV: foobaz
      APACHE_DOCUMENT_ROOT: /srv/web

  nginx:
    image: webdevops/php-nginx:alpine-3-php7
    volumes:
     - ./:/srv
    ports:
      - 83:80
    environment:
      MY_ENV: foobaz
      WEB_DOCUMENT_ROOT: /srv/web
