version: "3.3"

services:

  caddy:
    image: abiosoft/caddy:php
    volumes:
     - ./:/srv
     - ./Caddyfile:/etc/Caddyfile
    ports:
      - 81:2015
    environment:
      MY_ENV: foobaz

  react:
    image: php:7-alpine
    volumes:
     - ./:/srv
    ports:
      - 82:80
    command: /srv/bin/serve.php
    environment:
      MY_ENV: foobaz

  apache:
    image: php:7.0-apache
    volumes:
     - ./:/var/www
    ports:
      - 83:80
    command: /bin/bash -c 'a2enmod rewrite; apache2-foreground'
    environment:
      MY_ENV: foobaz

  nginx:
    image: webdevops/php-nginx:alpine-3-php7
    volumes:
     - ./:/app
    ports:
      - 84:80
    environment:
      MY_ENV: foobaz
      WEB_DOCUMENT_ROOT: /app/public
